// @ts-check
/**
 * Build-time service worker.
 *
 * The SW file is generated AFTER the build so it can carry a precache
 * list of the exact dist contents (every file Astro just wrote) plus a
 * build timestamp used as the cache version — a fresh deploy therefore
 * produces a byte-different sw.js, which is what makes the browser
 * notice there is an update at all.
 *
 * Caching strategy:
 *   - install  → precache every dist file (bypassing the HTTP cache),
 *                then take control immediately; a single failed fetch
 *                rejects the install so the worker retries next visit;
 *   - activate → delete every other `portfolio-*` cache (old deploys);
 *   - navigate → network first (HTML is the one asset that must
 *                outlive a deploy), cache fallback for offline, stored
 *                under one canonical key so anchors/queries/utm tags
 *                can't grow the page cache;
 *   - asset    → cache first (all dist assets are content-addressed or
 *                precached), network fill as backstop.
 *
 * Cross-origin requests (the project preview iframes) and Range
 * requests are never intercepted.
 *
 * Base-awareness: every URL is prefixed with the configured base, so
 * the same code serves `/madcoder/…` on GitHub Pages and `/…` on
 * Vercel.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

/** Recursively list every file under `dir`. */
const walk = async (dir) => {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
};

/** The generated worker source. Uses no template literals of its own,
 *  so nothing inside needs `${…}` escaping. */
const swSource = ({ version, prefix, precache }) => `// Generated by src/pwa.mjs during \`astro build\` — do not edit by hand.
// Cache version = build timestamp; every deploy yields a new byte
// stream, which is how the browser detects the update.
"use strict";

var VERSION = ${JSON.stringify(version)};
var CACHE = "portfolio-" + VERSION;
var PREFIX = ${JSON.stringify(prefix)};
var CORE = ${JSON.stringify(precache, null, 2)};

function offline() {
  return new Response("You are offline.", {
    status: 503,
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return Promise.all(
        CORE.map(function (url) {
          // cache: "reload" bypasses the HTTP cache — the precache must
          // reflect the files this build just wrote, not what a proxy
          // or the disk cache happens to hold.
          return fetch(new Request(url, { cache: "reload" })).then(function (res) {
            if (!res.ok) throw new Error("precache " + res.status + " " + url);
            return cache.put(url, res);
          });
        })
      );
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) {
            return key.indexOf("portfolio-") === 0 && key !== CACHE;
          })
          .map(function (key) { return caches.delete(key); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;
  var url;
  try { url = new URL(req.url); } catch (err) { return; }
  // Same origin only: the preview iframes open third-party demos and
  // must keep working exactly as they do without a service worker.
  if (url.origin !== self.location.origin) return;
  // Partial reads (PDF viewers, media) need real 206 responses.
  if (req.headers.has("range")) return;

  if (req.mode === "navigate") {
    event.respondWith(handleNavigate(event, req));
  } else {
    event.respondWith(handleAsset(event, req));
  }
});

function handleNavigate(event, req) {
  return fetch(req).then(function (fresh) {
    if (fresh.ok) {
      // One canonical key per site — a new successful load refreshes it
      // in place instead of accumulating entries per anchor/query.
      var copy = fresh.clone();
      event.waitUntil(
        caches.open(CACHE).then(function (cache) {
          return cache.put(new Request(PREFIX + "/"), copy);
        })
      );
    }
    return fresh;
  }).catch(function () {
    return caches.match(req, { ignoreSearch: true }).then(function (hit) {
      return hit || caches.match(PREFIX + "/", { ignoreSearch: true });
    }).then(function (hit) {
      return hit || caches.match(PREFIX + "/index.html", { ignoreSearch: true });
    }).then(function (hit) {
      return hit || offline();
    });
  });
}

function handleAsset(event, req) {
  return caches.match(req, { ignoreSearch: true }).then(function (hit) {
    if (hit) return hit;
    return fetch(req).then(function (res) {
      if (res.ok) {
        var copy = res.clone();
        event.waitUntil(
          caches.open(CACHE).then(function (cache) {
            return cache.put(req, copy);
          })
        );
      }
      return res;
    }).catch(function () { return offline(); });
  });
}
`;

export const pwa = () => {
  /** @type {string} */ let base = "/";
  /** @type {string} */ let outDir = "dist";

  return {
    name: "pwa:service-worker",
    hooks: {
      "astro:config:done": ({ config }) => {
        base = config.base;
        outDir = fileURLToPath(config.outDir);
      },
      "astro:build:done": async () => {
        // Prefix every dist path with the base — GitHub Pages serves the
        // repo under /madcoder/, Vercel from the domain root.
        const prefix = base === "/" ? "" : base.replace(/\/+$/, "");
        const files = (await walk(outDir)).map((file) =>
          relative(outDir, file).split(sep).join("/"),
        );
        const precache = files
          .filter((path) => path !== "sw.js" && !path.endsWith(".map"))
          .map((path) => encodeURI(`${prefix}/${path}`))
          .sort();
        // The bare directory URL as well: it is the offline fallback
        // key and must exist even though no file maps to it literally.
        precache.push(`${prefix}/`);

        const version = new Date().toISOString();
        await writeFile(join(outDir, "sw.js"), swSource({ version, prefix, precache }), "utf8");
        console.log(`  pwa  ${prefix}/sw.js  ${precache.length} precached assets`);
      },
    },
  };
};
